<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI0tg73f\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI0tg73f/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerI0tg73f.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerI0tg73f\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerI0tg73f\appProdProjectContainer([
    'container.build_hash' => 'I0tg73f',
    'container.build_id' => '15b86147',
    'container.build_time' => 1551684698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI0tg73f');
